# Generated by Django 5.1.4 on 2024-12-10 10:32

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="booking",
            name="additional_service",
            field=models.CharField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("consultation", "Consultation"),
                    ("repair", "Repair"),
                ],
                default="consultation",
                help_text="Type of additional service being booked.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                default=api.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customuser",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="password",
            field=models.CharField(default="123", help_text="Password", max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                default=api.models.get_default_service,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.service",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="123", help_text="Password", max_length=255),
        ),
    ]
