name: farm_link_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localization: ^0.2.3
  flutter_rating_bar: ^4.0.0
  google_fonts: ^6.2.1
  carousel_slider: ^4.0.0
  image_picker: ^0.8.8+7
  easy_localization: ^3.0.7
  razorpay_flutter: ^1.3.0 # Razorpay integration for Flutter
  http: ^1.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  lottie: ^3.2.0
  flutter_bloc: ^8.1.6
  animate_do: ^3.3.4
  vtable: ^0.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  sqflite: ^2.4.1
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  geolocator: ^13.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

