# Generated by Django 5.1.4 on 2024-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="image",
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
