# Generated by Django 5.1.4 on 2024-12-10 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_service_booking_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="created_at",
        ),
    ]
